name: Bug report
description: Create a bug report about Kaiteki
title: ""
labels: [ bug ]
body:
- type: textarea
  id: what
  attributes:
    label: What happened?
    placeholder: My computer exploded
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label: Expected behavior
    placeholder: For it to work
- type: textarea
  id: reproduction
  attributes:
    label: To Reproduce
    value: |
      1.
      2.
      3.
      ...
- type: checkboxes
  id: platform
  attributes:
    label: What platform are you seeing the issue on?
    options:
    - label: Android
    - label: Windows
    - label: Linux
    - label: Web
- type: textarea
  id: context
  attributes:
    label: Additional context