name: kaiteki
repository: 'https://github.com/Craftplacer/kaiteki'
issue_tracker: 'https://github.com/Craftplacer/kaiteki/issues'
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  animations: ^2.0.0
  async: ^2.9.0
  badges: ^2.0.1
  chewie: ^1.0.0
  crypto: ^3.0.1
  fediverse_objects:
    git: https://github.com/Kaiteki-Fedi/fediverse_objects.git
  file_picker: ^4.3.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.2.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  flutter_svg: ^1.0.1
  flutter_typeahead: ^4.0.0
  freezed: ^2.0.3+1
  go_router: ^3.0.1
  google_fonts: ^3.0.0
  html: ^0.15.0
  http: ^0.13.1
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  json_annotation: any
  logger: ^1.0.0
  mdi: ^5.0.0-nullsafety.0
  oauth1: ^2.0.0
  palette_generator: ^0.3.2
  shared_preferences: ^2.0.5
  shelf: ^1.3.0
  state_notifier: ^0.7.1
  supercharged: ^2.0.0
  tuple: ^2.0.0
  url_launcher: ^6.0.3
  uuid: ^3.0.6
  video_player: ^2.1.0
  widgetbook_annotation: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^2.0.1
  json_serializable: ^6.0.1
  msix: ^3.5.1
  test: ^1.17.10
  widgetbook: ^2.3.0
  widgetbook_generator: ^2.2.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/mastodon.png
    - assets/icons/pleroma.png
    - assets/icons/misskey.png
    - assets/icons/husky.png
    - assets/icon.png
    - assets/credits.json
    - assets/instances.json
    - assets/oauth-success.html
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true

msix_config:
  display_name: Kaiteki
  publisher_display_name: Craftplacer
  identity_name: Craftplacer.Kaiteki
  msix_version: 1.0.0.0
  # certificate_path: C:\<PathToCertificate>\<MyCertificate.pfx>
  # publisher: CN=My Company, O=My Company, L=Berlin, S=Berlin, C=DE
  logo_path: ..\..\assets\icons\windows\kaiteki.png
  start_menu_icon_path: ..\..\assets\icons\windows\kaiteki.png
  tile_icon_path: ..\..\assets\icons\windows\kaiteki.png
  # vs_generated_images_folder_path: C:\<PathToFolder>\Images
  icons_background_color: '#1e2133'
  architecture: x64
  capabilities: 'internetClient'