name: Linux

env:
  SOURCE_PATH: './src/kaiteki'

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: dev

      - name: Install Linux build requirements
        run: 'sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev'

      - name: Enable Linux Desktop
        run: 'flutter config --enable-linux-desktop'

      - name: Get packages
        working-directory: ${{ env.SOURCE_PATH }}
        run: 'flutter pub get'

      - name: Build
        working-directory: ${{ env.SOURCE_PATH }}
        run: 'flutter build linux'
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: '${{ env.SOURCE_PATH }}/build/linux/release/bundle/'