name: Build and deploy

on:
  workflow_dispatch

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: dev

      - name: Install Linux build requirements
        run: 'sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev'

      - name: Enable Linux Desktop
        run: 'flutter config --enable-linux-desktop'

      - name: Get packages
        working-directory: 'src'
        run: 'flutter pub get'

      - name: Build
        working-directory: 'src'
        run: 'flutter build linux'
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: |
            './src/build/linux/release/kaiteki'
            './src/build/linux/**/*.so'
            '!./src/build/linux/**/*cmake*'
  
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        
      - name: Get packages
        working-directory: 'src'
        run: 'flutter pub get'

      - name: Build
        working-directory: 'src'
        run: 'flutter build apk --split-per-abi'
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: android
          path: './src/build/app/outputs/apk/release/*.apk'

  build-web:
    name: Build for Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: beta

      - name: Enable web
        run: flutter config --enable-web
        
      - name: Get packages
        working-directory: 'src'
        run: 'flutter pub get'
      
      - name: Build
        working-directory: 'src'
        run: 'flutter build web'
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: './src/build/web/*'
          
  release-web:
    name: Deploy for Web
    runs-on: ubuntu-latest
    needs: build-web
    steps:
    - name: Download web artifact
      uses: actions/download-artifact@v2
      with:
        name: web
        path: ./web-publish

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web-publish

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ build-linux, build-android ]
    steps:
      - name: Download Android APKs
        uses: actions/download-artifact@v2
        with:
          name: android
          path: ./release

      - name: Download Linux binaries
        uses: actions/download-artifact@v2
        with:
          name: linux
          path: ./release-linux
      
      - name: Repackage Linux artifacts
        uses: edgarrc/action-7z@v1.0.4
        with:
          args: 7z a ./linux.zip ./release-linux
        
      - name: Add repackaged artifacts to release directory
        run: mv ./linux.zip ./release

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Development build
          files: release/*
