name: "Check for TODOs"
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO-2-GH-Issue"
        uses: "jamminroot/todo-2-gh-issue@master"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TODO_PATTERN: "(?<=\\/\\/ ?TODO[ :]).+"
          GH_LABEL: "todo"
          TRIM: ",: \""
          TIMEOUT: 1000
          LINES_BEFORE: 2
          LINES_AFTER: 5
          LABELS_PATTERN: "(?<=\\[).+?(?=\\])"
          LABELS_REPLACE_PATTERN: "\\[(.+?)\\]"
          IGNORED_LINES_LENGTH: 255
          INCLUDED_PATHS: /src/
          FILE_PATTERN: "*.dart"
        id: "todo"
