name: Build and deploy to Web
env:
  SOURCE_PATH: './src/kaiteki'

on:
  workflow_dispatch
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: beta

      - name: Enable web
        run: flutter config --enable-web
        
      - name: Get packages
        working-directory: ${{ env.SOURCE_PATH }}
        run: 'flutter pub get'
      
      - name: Build
        working-directory: ${{ env.SOURCE_PATH }}
        run: 'flutter build web'
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: '${{ env.SOURCE_PATH }}/build/web/*'
          
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-web
    steps:
    - name: Download web artifact
      uses: actions/download-artifact@v2
      with:
        name: web
        path: ./web-publish

    - name: Push to GitHub Pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web-publish
