name: Windows

env:
  SOURCE_PATH: '.\src\kaiteki'

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ${{ env.SOURCE_PATH }}
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 600
          
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: beta
        
      - name: Enable Windows Desktop
        run: 'flutter config --enable-windows-desktop'

      - name: Get packages
        run: 'flutter pub get'

      - name: Build
        run: 'flutter build windows --release'
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: '${{ env.SOURCE_PATH }}/build/windows/runner/Release/'

#  package:
#    name: Package
#    runs-on: windows-latest
#    needs: build
#    steps:
#      - name: Download artifacts
#        uses: actions/download-artifact@v2
#        with:
#          name: windows
#          path: '${{ env.SOURCE_PATH }}/build/windows/runner/Release/'
#
#      - name: Setup Flutter
#        uses: subosito/flutter-action@v1
#
#      - name: Package
#        working-directory: ${{ env.SOURCE_PATH }}
#        run: 'flutter pub run msix:create'
#
#      - name: Upload artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: windows-msix
#          path: '${{ env.SOURCE_PATH }}/build/windows/runner/Release/kaiteki.msix'
#